"+=x/,? 73 just testing you.",
",?/=+9 73 just testing you.",
",?/=q+ 73 just testing u.",
"8y67fvgb oops cat on keyboard.",
"9p0ojgbhnw23 oops cat on keyboard.",
"a clumsy gecko just fell on my hand.",
"are you a communist?",
"are you a democrat?",
"are you a libertarian?",
"are you a republican?",
"are you divorced?",
"are you good at auto repair?",
"are you good at calculus? i have a question for you.",
"are you good at car repair? i have a question for you.",
"are you good at group theory? i have a question for you.",
"are you good at summing infinite series?",
"are you married?",
"are you on daylight savings time?",
"are you single?",
"are you using a linear amplifier?",
"are you using an iambic key?",
"are you widowed?",
"aye, laddie, have you ever been to sea?",
"can you pick kryptonite locks? those are tricky.",
"can you pick kryptonite locks?",
"can you pick master locks? those are supposed to be easy.",
"can you think of something else interesting to say?",
"copy?",
"cpy?",
"did you attend oru?",
"did you hear news?",
"did you hear the news?",
"do u understand english?",
"do you have a baby?",
"do you have a cat?",
"do you have a dog?",
"do you have a ferret?",
"do you have a gecko?",
"do you have a horse?",
"do you know morse code?",
"do you know the word copacetic?",
"do you know the word garrulous?",
"do you know the word prosy?",
"do you know what a pangram is?",
"do you like bach?",
"do you like bernstein?",
"do you like c and w music?",
"do you like classical music?",
"do you like country music?",
"do you like hawaiian music?",
"do you like jawaiian music?",
"do you like modern rock?",
"do you like mozart?",
"do you like pop music?",
"do you like reggae music?",
"do you like rock music?",
"do you like swing music?",
"do you listen to deutsche welle?",
"do you listen to radio australia?",
"do you listen to radio moscow?",
"do you listen to radio new zealand intl?",
"do you listen to radio peace peoples republic of korea?",
"do you listen to voa?",
"do you listen to click and clack on pbs?",
"do you listen to the bbc?",
"do you prefer metric units?",
"do you recycle often?",
"do you understand english?",
"do you watch quantum leap?",
"do you watch sttng?",
"do you watch simpsons?",
"gaverete ruskie?",
"habla espanol?",
"has the war started yet?",
"have a nice t day.",
"have a nice thanksgiving.",
"have you been to hawaii recently?",
"have you been to kauai since iniki?",
"have you ever been to new madrid, missouri?",
"have you ever been to the chatham islands?",
"have you ever contacted kalawao county, molokai?",
"have you ever contacted loving county, texas?",
"have you ever played lemmings?",
"have you ever played tetris?",
"have you ever seen a computer virus?",
"how copy so far?",
"how copy?",
"how did you learn morse code?",
"how is my signal?",
"how is the weather?",
"how long have you been a radio amateur?",
"how old is your rig?",
"hows my signal?",
"hows the weather?",
"i am mobile and am going to the office.",
"i am mobile and am going to work.",
"i am mobile and driving to work.",
"i am mobile, driving cross country.",
"i am mobile, driving home from work.",
"i am mobile, riding a peruvian paso fino horse.",
"i am mobile, riding a peruvian paso horse.",
"i am mobile, stuck in traffic.",
"i am using a linear amplifier.",
"i am using an iambic key.",
"i just saw a bolide.",
"i live at 10 downing.",
"i live at 1010 springwood.",
"i live at 1620 keeaumoku.",
"i live at 2500 pennsylvania.",
"i live at 61c escondido.",
"i sometimes monitor ulf for earthquake precursors.",
"i sometimes monitor ulf for earthquake precursors.",
"i sometimes work packet on vhf.",
"is it green there or brown?",
"is the bad news true?",
"is your state the one that doesnt have any city governments?",
"is your state the one that has a unicameral legislature?",
"is your state the one that has boroughs instead of counties?",
"is your state the one that has parishes instead of counties?",
"is your state the one that has townships instead of counties?",
"ive fallen and i cant get up.",
"jocks find quartz glyph, vex bmw.",
"jocks find quartz glyph, vex bmw.",
"jocks find quartz glyph, vex bmw.",
"lots of qrm.",
"mele kelikimaka and hauoli makahiki hou 1995.",
"must qrt for babylon v.",
"must qrt for star trek.",
"must qrt for bathroom break.",
"must qrt for breakfast.",
"must qrt for cold breakfast.",
"must qrt for cold dinner.",
"must qrt for cold supper.",
"must qrt for diarreah break.",
"must qrt for dinner.",
"must qrt for hot breakfast.",
"must qrt for hot dinner.",
"must qrt for hot lunch.",
"must qrt for hot supper.",
"must qrt for lunch.",
"must qrt for sleep.",
"must qrt for some sleep.",
"must qrt for supper.",
"must qrt invading tanks making too much noise outside to hear you.",
"must qrt occupation forces knocking at door.",
"must qrt to hear news about approaching hurricane.",
"must qrt wind has blown door open again.",
"must qrt, lightning storm has started.",
"must qrt, lightning threatens.",
"must qrt, nuclear attack?",
"must qrt, tornado sirens sounding.",
"must qrt, tsunami sirens sounding.",
"must qrt, weather radio warbling.",
"our neighbors have a horse named morse code.",
"our neighbors have a horse named morse.",
"please qrs.",
"propagation is good.",
"propagation is poor.",
"propagation is very good.",
"propagation is very poor.",
"qlf?",
"qrg",
"qrh",
"qri 1",
"qri 2",
"qri 3",
"qri",
"qrj",
"qrk 1",
"qrk 2",
"qrk 3",
"qrk 4",
"qrk 5",
"qrk",
"qrl",
"qrm",
"qrm?",
"qrn 1",
"qrn 2",
"qrn 3",
"qrn 4",
"qrn 5",
"qrn",
"qro",
"qrp",
"qrp?",
"qrq 10",
"qrq 15",
"qrq 20",
"qrq 5",
"qrq",
"qrs 10",
"qrs 15",
"qrs 20",
"qrs 5",
"qrs",
"qrs?",
"qru",
"qrv",
"qrw",
"qrx 0300",
"qrx 0500",
"qrx 2000",
"qrx 2300",
"qrx",
"qrx?",
"qry 1",
"qry 2",
"qry 3",
"qry",
"qrz",
"qsa 1",
"qsa 2",
"qsa 3",
"qsa 4",
"qsa 5",
"qsa",
"qsb",
"qsd",
"qsg 1",
"qsg 2",
"qsg",
"qsk",
"qsk?",
"qsl",
"qsm",
"qsn",
"qso",
"qsp",
"qst",
"qsu",
"qsw",
"qsx",
"qsy",
"qsy?",
"qsz",
"qtb",
"qtc",
"qth?",
"qtr",
"qtr?",
"should we qsy?",
"so how is the weather?",
"sorry, stack of books just fell over.",
"sprechen sie deutsch?",
"thanks for the call.",
"there is a rainbow outside the window.",
"there is an eclipse of the moon right now.",
"tnx for the call.",
"tnx for the report.",
"tnx for ur call.",
"we are on vacation and i am mobile.",
"we just felt a small quake here.",
"what are your hobbies?",
"what is the air pressure there?",
"what is the air quality there?",
"what is the air temperature there?",
"what is the humidity there?",
"what is your qth?",
"what is your elevation?",
"what is your hobby?",
"what is your job?",
"what is your sign? i am a cancer.",
"what is your sign? i am a centaur.",
"what is your sign? i am a fish.",
"what time zone are you in?",
"whats your job?",
"when did you start to learn morse code?",
"where do you live now?",
"where do you live?",
"where is hollister, california anyway?",
"where is parkfield, california anyway?",
"whoa, we are having an earthquake here. a real roller.",
"would you have given morse a nobel prize?",
"you are my first contact today.",
"you are my last contact today.",
"you are my second contact today.",
"you are using a nonlinear amplifier?",
"you are using an iambic key?",
"your contest sequence no is 1035.",
"your contest sequence no is 12.",
"your contest sequence no is 17.",
"your contest sequence no is 479.",
"your contest sequence no is 73.",
"your contest sequence no is 7v.",
"your contest sequence no is 826.",
"your contest sequence no is 99.",
"your job is?",
"your signal is chirpy.",
"am using a linear amplifier.",
"ewsqgbhjolpi oops cat on keyboard.",
"ru using linear amplifier?",
